### ISSUE TITLE
Error while executing: Downloading hermetic hadolint v2.12.0

### ISSUE THREAD

**Issue by thetacom** [trunk-io/plugins#239]
title: "Error while executing: Downloading hermetic hadolint v2.12.0"
report:
  - HTTP 404 'https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Darwin-arm64'

**Comment by TylerJang27** [comment]
Hi! Thanks for highlighting this. We actually just landed a fix for this issue: #237. We should have a release out in the next few days with the fix. I will close the issue when that happens.

**Comment by TylerJang27** [comment]
In the meantime, to stop seeing this error, you can temporarily change the ref in your `.trunk/trunk.yaml` to use the sha at HEAD, rather than the release (you'll want to manually change it back when `v0.0.15` is released):

```yaml
version: 0.1
plugins:
  sources:
    - id: trunk
      uri: https://github.com/trunk-io/plugins
      ref: 0b97076fbf2962de26baa5e077014758c7be1b72
```

If you don't want to commit this change to your repo, you can temporarily add this snippet to `.trunk/user.yaml`.
