### ISSUE TITLE
Clang-tidy doesn't work from VSCode

### ISSUE THREAD

**Issue by sr-tream** [trunk-io/plugins#471]
```yml
trunk_cli_version: 1.15.0
title: "Error while executing: Querying compile commands"
report:
  - "[json.exception.type_error.302] type must be string, but is number"
```

I tried to place `compile_commands.json` in:
1. root workspace
2. folder build in root workspace
3. folder with current cpp file

Anything does not work
