### ISSUE TITLE
Is there a way to override a plugin configuration from a trunk configuration? (or: add svelte support)

### ISSUE THREAD

**Issue by fnimick** [trunk-io/plugins#475]
Currently, I am not able to configure Trunk to use `eslint` and `prettier` to check `*.svelte` files. These linters have Svelte support via plugins.

**Comment by TylerJang27** [comment]
Hi! Fortunately Trunk is fully customizable via config. You can add the following overrides to your `.trunk/trunk.yaml`:

```yaml
lint:
  files:
    - name: svelte
       extensions:
         - svelte
      comments:
        - html-tag
  definitions:
    - name: eslint
       files:
         - typescript
         - javascript
         - svelte
    - name: prettier
      files:
        - typescript
        - yaml
        - css
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
        - svelte
```

We don't do this out of the box since it requires users to install those specific plugins. If you want to use this override across several repos and not just one, you can achieve this through your own [plugin repo](https://docs.trunk.io/plugins#plugins-scope).

If you run into any trouble, feel free to follow-up here, or you can hop over to our [community Slack](https://slack.trunk.io/) to get more direct support if you'd like.
