### ISSUE TITLE
Visual Studio Code Extension thinks autopep8 2.0.4 needs to be upgraded to 2.0.4

### ISSUE THREAD

**Issue by error9900** [trunk-io/plugins#507]
This is what I get after running the linter upgrade:
![image](https://github.com/trunk-io/plugins/assets/19411194/493a1b53-d0c9-4466-8931-8f2ef6b6d197)

And then after that, the Trunk Side Panel continuously shows there is an upgrade available:
![image](https://github.com/trunk-io/plugins/assets/19411194/d76b2fd1-5e44-4a1c-b1a0-4197bc42d31d)

**Comment by TylerJang27** [comment]
Hi there, thanks for reporting this! Do you mind posting the contents of your .trunk/trunk.yaml after this upgrade? This will help us get to the bottom of what's happening with this issue. Thanks!

**Comment by error9900** [comment]
Hmm. Interesting...

Here's .trunk/trunk.yaml before enabling autopep8:
```
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.16.2
plugins:
  sources:
    - id: trunk
      ref: v1.2.5
      uri: https://github.com/trunk-io/plugins
runtimes:
  definitions:
    - type: python
      system_version: allowed
lint:
  disabled:
    - semgrep
    - ruff
    - yapf
    - pylint
    - mypy
    - flake8
    - bandit
    - pyright
    - sourcery
  enabled:
    - black@23.9.1
    - checkov@2.5.4
    - codespell@2.2.6
    - cspell@7.3.7
    - git-diff-check
    - gitleaks@8.18.0
    - isort@5.12.0
    - markdownlint@0.37.0
    - osv-scanner@1.4.0
    - prettier@3.0.3
    - remark-lint@12.0.0
    - taplo@0.8.1
    - trivy@0.45.1
    - trufflehog@3.59.0
    - yamllint@1.32.0
  ignore:
    - linters: [ALL]
      paths:
        - old_code/
actions:
  disabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trufflehog-pre-commit
    - commitlint
  enabled:
    - trunk-upgrade-available
```

After enabling autopep8:
```
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.16.2
plugins:
  sources:
    - id: trunk
      ref: v1.2.5
      uri: https://github.com/trunk-io/plugins
runtimes:
  definitions:
    - type: python
      system_version: allowed
lint:
  disabled:
    - semgrep
    - ruff
    - yapf
    - pylint
    - mypy
    - flake8
    - bandit
    - pyright
    - sourcery
  enabled:
    - autopep8@2.0.4
    - black@23.9.1
    - checkov@2.5.4
    - codespell@2.2.6
    - cspell@7.3.7
    - git-diff-check
    - gitleaks@8.18.0
    - isort@5.12.0
    - markdownlint@0.37.0
    - osv-scanner@1.4.0
    - prettier@3.0.3
    - remark-lint@12.0.0
    - taplo@0.8.1
    - trivy@0.45.1
    - trufflehog@3.59.0
    - yamllint@1.32.0
  ignore:
    - linters: [ALL]
      paths:
        - old_code/
actions:
  disabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trufflehog-pre-commit
    - commitlint
  enabled:
    - trunk-upgrade-available
```

The Upgrade Available shows up in the Side Panel, and after I hit Run:
```
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.16.2
plugins:
  sources:
    - id: trunk
      ref: v1.2.5
      uri: https://github.com/trunk-io/plugins
runtimes:
  enabled:
    - go@1.21.0
    - node@18.12.1
    - python@3.10.8
  definitions:
    - type: python
      system_version: allowed
lint:
  disabled:
    - semgrep
    - ruff
    - yapf
    - pylint
    - mypy
    - flake8
    - bandit
    - pyright
    - sourcery
  enabled:
    - autopep8@2.0.4
    - black@23.9.1
    - checkov@2.5.4
    - codespell@2.2.6
    - cspell@7.3.7
    - git-diff-check
    - gitleaks@8.18.0
    - isort@5.12.0
    - markdownlint@0.37.0
    - osv-scanner@1.4.0
    - prettier@3.0.3
    - remark-lint@12.0.0
    - taplo@0.8.1
    - trivy@0.45.1
    - trufflehog@3.59.0
    - yamllint@1.32.0
  ignore:
    - linters: [ALL]
      paths:
        - old_code/
actions:
  disabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trufflehog-pre-commit
    - commitlint
  enabled:
    - trunk-upgrade-available
```

It's adding runtimes for go, node, & python. Not sure if that's expected behavior...
