### ISSUE TITLE
Custom Dictionaries seem to break `cspell`

### ISSUE THREAD

**Issue by error9900** [trunk-io/plugins#538]
I'm running this command for all 3 scenarios:

```
trunk check --all --filter cspell
```

-----

# Scenario 1

`cspell.yaml`:

```
version: "0.2"
suggestionsTimeout: 5000
```

Result: `94 issues`

-----

# Scenario 2

`cspell.yaml`:

```
version: "0.2"
suggestionsTimeout: 5000
dictionaries:
  - python
```

Result: `69 issues`

-----

# Scenario 3

`cspell.yaml`:

```
version: "0.2"
suggestionsTimeout: 5000
dictionaryDefinitions:
  - name: cspell-custom-dict
    path: ./cspell-custom-dict.txt
dictionaries:
  - cspell-custom-dict
```

Result: `No issues`[^1]

[^1]: This happens with an empty `cspell-custom-dict.txt`, and also with a single word in it.

-----

# Other Info

Reference Config:
- https://github.com/streetsidesoftware/cspell/blob/main/examples/cspell.config.yaml
- https://cspell.org/docs/dictionaries-custom/

---

`trunk.yaml`:

```
---
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file,
# see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.17.1
plugins:
  sources:
    - id: trunk
      ref: v1.2.6
      uri: https://github.com/trunk-io/plugins
runtimes:
  definitions:
    - type: python
      system_version: allowed
lint:
  disabled:
    - autopep8
    - checkov
    - pyright
    - sourcery
    - yapf
  enabled:
    - flake8@6.1.0
    - bandit@1.7.5
    - black@23.9.1
    - codespell@2.2.6
    - cspell@7.3.8
    - dustilock@1.2.0
    - git-diff-check
    - gitleaks@8.18.0
    - isort@5.12.0
    - markdownlint@0.37.0
    - mypy@1.6.1
    - osv-scanner@1.4.2
    - prettier@3.0.3
    - pylint@3.0.2
    - remark-lint@12.0.0
    - ruff@0.1.2
    - semgrep@1.45.0
    - taplo@0.8.1
    - trivy@0.46.0
    - trufflehog-git@3.60.3
    - trufflehog@3.60.3
    - yamllint@1.32.0
actions:
  disabled:
    - commitlint
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
  enabled:
    - trufflehog-pre-commit
    - trunk-upgrade-available
```

**Comment by TylerJang27** [comment]
Hi, sorry for the delay. I suspect that what is happening is `cspell` is not reporting an issue if it can't locate `./cspell-custom-dict.txt`. Can you add the following override to your trunk.yaml and let me know if the issue resolves? This is necessary in order for Trunk's sandboxed execution to take into account all the necessary inputs:

```yaml
lint:
  definitions:
    - name: cspell
       affects_cache:
        - package.json
        - cspell-custom-dict.txt
```

Unfortunately this isn't something we can autocompute by default because it requires awareness of each linter's own config schema.
