### ISSUE TITLE
`direct_configs` doesn't work for `tflint`

### ISSUE THREAD

**Issue by wzooff** [trunk-io/plugins#565]
I have custom `tflint` config in the root of my git repository. What I've noticed, is that `tflint` doesn't use it, if i try to specify it via [`direct_configs`](https://github.com/trunk-io/plugins/blob/main/linters/tflint/plugin.yaml#L47) like this
```yaml
lint:
  definitions:
    - name: tflint
      direct_configs: 
       - .tflint.hcl
       - ${workspace}/.tflint.hcl # doesn't work
```
tbh, I haven't find any clear description for `direct_configs` attribute, so still not sure that this is proper place to specify custom config location

Current workaround for me is to specify config dir via env variable
```yaml
lint:
  definitions:
    - name: tflint
      environment:
        - name: TFLINT_CONFIG_FILE
          value: ${workspace}/.tflint.hcl
```
or via `--config` argument 
```yaml
lint:
  definitions:
    - name: tflint
      commands:
        - name: lint
          run: tflint --format=sarif --chdir=${target} --force --config=${workspace}/.tflint.hcl
```

## Info

paths:
- `${workspace}/.trunk/trunk.yaml`
- `${workspace}/.tflint.hcl`

versions
- trunk@1.17.2
- tflint@0.49.0

**Comment by TylerJang27** [comment]
Hi @wzooff! Thanks for reporting this. This issue came to our attention recently from another user. Specifically the problem is that tflint uses `--chdir` differently than most of our other linters wrt subdirectories. The environment override you specified is the best workaround for now. Nevertheless, this is definitely something we're prioritizing to fix. I'll keep this thread updated as we make progress.

**Comment by TylerJang27** [comment]
Upon a further audit, we intend to leave the current implementation as-is and provide additional documentation. To give a bit of an overview and explanation:
- tflint only runs on the current directory, including loading configuration from the [current directory](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md). Even if [`--chdir`](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/working-directory.md) is used, tflint loads config from the target directory, not the current directory. As such, when running on a sample repo with the following structure:

```
.tflint.hcl
a/
  a1.tf
  a2.tf
b/
  .tflint.hcl
  b1.tf
  b2.tf
```
...running `tflint --recursive` will load `b/.tflint.hcl` when scanning `b/`, but will not load `.tflint.hcl` when scanning `a/` (it will use the tflint internal default config instead).

- Accordingly, tflint is intended to be configured by the target directory it runs on, not where it runs from.
- When trunk runs linters and copies in configuration files from `.trunk/configs`, they are symlinked into the sandbox workspace root. This feature is intended to reduce the clutter of `./`. When tflint is running on a nested directory, it has no notion of the workspace root to begin with. 
- Thus, it seems inappropriate for Trunk to inject a config from `.trunk/configs` into each nested directory, when this is not the intended tflint functionality.
- **Rather, this will be available as an opt-in feature**, using the overrides identified above, particularly:
```yaml
lint:
  definitions:
    - name: tflint
      environment:
        - name: TFLINT_CONFIG_FILE
          value: ${workspace}/.tflint.hcl # or ${workspace}/.trunk/configs/.tflint.hcl
```

I will be adding repo documentation accordingly. If we receive additional feedback we may revisit this approach in the future.
