### ISSUE TITLE
Update Rome to Biome

### ISSUE THREAD

**Issue by texastoland** [trunk-io/plugins#599]
Replaced [since August](https://biomejs.dev/blog/annoucing-biome/#i-still-use-the-rome-package-what-should-i-do).

It also [supports JSON](https://biomejs.dev/internals/language-support/).

**Comment by TylerJang27** [comment]
Hi! Thanks for bringing this to our attention! We support a lot of linters and formatters so sometimes things like this can be overlooked. We will continue to support rome as a legacy linter+formatter, but I will look into adding support for Biome this week!

**Comment by TylerJang27** [comment]
I've just landed support for Biome! If you'd like to start using it immediately, you can modify your `.trunk/trunk.yaml` like so:
```yaml
plugins:
  sources:
    - id: trunk
      uri: https://github.com/trunk-io/plugins
      ref: 182dd26f62df82c08cb363c96615cc9926a58ba4
```

Otherwise, it will be included in the next release!
