### ISSUE TITLE
clippy fails without Cargo.lock present

### ISSUE THREAD

**Issue by nwesterhausen** [trunk-io/plugins#600]
Hello,

Was trying trunk out on a rust library and per best practices for libraries, Cargo.lock is not part of the repository. So while trunk runs fine locally after I have built the library once, it fails in CI. It also fails locally if I delete Cargo.lock first. This happens because the command for the clippy linter has "--locked" as part of the command which doesn't permit changing (or creating by extension?) the Cargo.lock file. And because of this, clippy errors.

I looked through your documentation but what I saw about configuring plugins appeared to be only what options are defined in the plugin.yaml file. However, the locked flag is hard-coded and not affected by any values that I saw when looking in the plugins repo.

If I'm missing something, I apologize but I did investigate as best I could.

trunk output:

```yml
trunk_cli_version: 1.18.1
title: "Error while executing: lib"
report:
  - Unable to find lib for Cargo.lock in any parent directory of /Volumes/LaCie/Repos/dfraw_json_parser/lib
  - linter:
      command: |
        /Users/nwesterhausen/.cache/trunk/tools/rust/1.65.0-e995c0a94cbb3cb0410a49183f3ef2b7/bin/cargo clippy --message-format json --locked -- --cap-lints=warn --no-deps
      stdin_path: (none)
      run_from: /Volumes/LaCie/Repos/dfraw_json_parser/lib
      timeout: 10m
      rerun: (cd /Volumes/LaCie/Repos/dfraw_json_parser/lib; env -i PATH=/Users/nwesterhausen/.cache/trunk/tools/rust/1.65.0-e995c0a94cbb3cb0410a49183f3ef2b7/bin:/Users/nwesterhausen/.opam/default/bin:/Users/nwesterhausen/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/nwesterhausen/.opam/default/bin:/Users/nwesterhausen/Library/pnpm:/Users/nwesterhausen/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nwesterhausen/.cargo/bin CARGO_TARGET_DIR=/Users/nwesterhausen/.cache/trunk/repos/a3e74e59ed19111a76af0d59e8fcaafe/results/clippy-current/cargo_target_dir CARGO_HOME=/Users/nwesterhausen/.cache/trunk/repos/a3e74e59ed19111a76af0d59e8fcaafe/results/clippy-current/cargo_home HOME=/Users/nwesterhausen /Users/nwesterhausen/.cache/trunk/tools/rust/1.65.0-e995c0a94cbb3cb0410a49183f3ef2b7/bin/cargo clippy --message-format json --locked -- --cap-lints=warn --no-deps)
      affects_cache:
        - Cargo.toml
      direct_configs:
        []
      exit_status: exited
      exit_code: 101
      stdout: (none)
      stderr: |
            Updating crates.io index
        error: the lock file /Volumes/LaCie/Repos/dfraw_json_parser/Cargo.lock needs to be updated but --locked was passed to prevent this
        If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.

    parser: |
      (none)
```

**Comment by det** [comment]
It looks like the Rust team has changed their guidance on this issue, please see the following: https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html

If you want to continue to not commit your `Cargo.lock`, you can modify the command that trunk uses to run clippy by merging the following into your `trunk.yaml`:
```
lint:
  definitions:
    - name: clippy
      commands:
        - name: lint
          run: cargo clippy --message-format json --locked -- --cap-lints=warn --no-deps
 ```
This is the current command we run, so you would want to remove `--locked`. Note that this should be merged into your config, and not appended. You will already have a `lint:` section, so you would nest the definitions in the current one.

Thanks for your interest in trunk and please let us know if this works for you.
