### ISSUE TITLE
Is there a way to use a bandit.yaml with the bandit linter?

### ISSUE THREAD

**Issue by jmontleon** [trunk-io/plugins#647]
I'd like to disable B101 for tests per:

https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html#module-bandit.plugins.asserts
```
You can configure files that skip this check. This is often useful when you use assert statements in test cases.

assert_used:
  skips: ['*_test.py', '*test_*.py']
```

Right now, if I understand correctly, we can only use a .bandit ini file. As far as I can tell only has the ability to skip files or disable checks across for the entire repo.

https://github.com/trunk-io/plugins/blob/main/linters/bandit/plugin.yaml#L20

**Comment by TylerJang27** [comment]
Hi @jmontleon! We only support `.bandit` files in our default configuration, but fortunately Trunk is fully configurable so you can specify some overrides to use a bandit.yaml file. Your `.trunk/trunk.yaml` should look something like this:

```yaml
lint:
  definitions:
    - name: bandit
      direct_configs: [bandit.yaml]
      commands:
        - name: lint
           run: bandit --exit-zero -c bandit.yaml --format json --output ${tmpfile} ${target}
```

Let me know if that works for you!
