### ISSUE TITLE
VS Code warning about soon-to-be-dropped code action

### ISSUE THREAD

**Issue by philsherry** [trunk-io/plugins#724]
Quick fixes have stopped working for me. 

<img width="710" alt="VS Code saying “Checking for quick fixes...”" src="https://github.com/trunk-io/plugins/assets/272769/37051095-d515-49fd-96d7-e962377c4ebc">

Now I just get stuck on “Checking for quick fixes...” and the following warning in the Extension Host console:

```log
[warning] trunk.io - Code actions of kind 'quickfix 'requested but returned code action is of kind 'source.fixAll'. 
Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
```

```yaml
cli:
  version: 1.21.0
plugins:
  sources:
    - id: trunk
      ref: v1.4.5
```
