### ISSUE TITLE
Request: add 'postcss' file support to prettier plugin

### ISSUE THREAD

**Issue by fnimick** [trunk-io/plugins#738]
e.g. sveltekit uses `*.postcss` files to trigger automatic postcss processing when using the default vite preprocessor. Prettier supports formatting these files.

**Comment by TylerJang27** [comment]
Hi! Thanks for bringing this up! I've gone ahead and put up #740. It may be a little while before our next release, but in the meantime you can add the following to your `.trunk/trunk.yaml` to take advantage of this immediately:
```yaml
lint:
  files:
    - name: postcss
      extensions:
        - pcss
        - postcss
  definitions:
    - name: prettier
      files: 
        - typescript
        - yaml
        - css
        - postcss
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
```
