### ISSUE TITLE
markdownlint config doesn't seem to be respected

### ISSUE THREAD

**Issue by sheldonhull** [trunk-io/plugins#788]
Trunk doesn't seem to honor the markdownlint config changes I've made.

[link](https://github.com/trunk-io/plugins/blob/7e583c8380937e45e99f31cebf2149a41aaccf54/linters/markdownlint/plugin.yaml#L24C1-L31C35) to example of mapping. 

I've tried a lot of variations but I can't get trunk to honor .markdownlint.yaml
I run the markdownlint vscode plugin and it honors the file, but in repo when I tweak it seems to ignore the file. 

For example changing indentation level to 12, it works with markdownlint tool itself, but then using trunk as my formatter it seems to go back to standard config and not honor it. 
I've tried both .markdownlint.yaml and .markdownlint.jsonc and neither seems to be picked up.
I've also tried placing in root of repo and copying to .trunk/configs and no change in behavior. 

![image](https://github.com/trunk-io/plugins/assets/3526320/c9fb22bb-2ecf-493a-a3f1-a36f329a8acc)

Trunk config

```yaml
version: '0.1'
cli:
  version: 1.22.1
plugins:
  sources:
    - id: trunk
      ref: v1.5.0
      uri: https://github.com/trunk-io/plugins
lint:
  enabled:
    - markdownlint@0.40.0

```

`.markdownlint.yaml`

```yaml
$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
MD007:
  indent: 12
  start_indented: false
  start_indent: 4
```

```markdown
- [ ] one
  - _In use by:_
    - this
- [ ] more detail
  - _the result_
    - more
    - foo
```

```markdown
- [ ] one
            - _In use by:_
                        - this
- [ ] more detail
            - _the result_
                        - more
                        - foo
```
