### ISSUE TITLE
[Trunk Check VSCode extension] plugin load failed; expected plugin.yaml to be present in plugin root

### ISSUE THREAD

**Issue by remkolems** [trunk-io/plugins#800]
I need some guidance in solving this issue.

I have an unexpected (for me) new issue  after working with this extension for a couple of months now within `.trunk/trunk.yaml`:

![image](https://github.com/trunk-io/plugins/assets/45675902/77ede03b-8d14-445f-8f11-b409dd99a530)

So I tested out the command (found on https://github.com/trunk-io/docs/tree/main/check/advanced-setup/plugins) in the root of my project to force a configuration update and ultimately the creation of missing `plugin.yaml`.

`trunk plugins add https://github.com/trunk-io/plugins v1.2.6 --id=trunk`

but the command also returns an error:

```shell
> trunk plugins add https://github.com/trunk-io/plugins v1.5.0 --id=trunk1
✖ plugin operations require a valid trunk config
```

Details
- Force updated to latest `trunk --version`: 1.21.0
- Force updated VSCode extension: Trunk Check v3.18.0
- VSCode: v1.90.0 (on Windows remote SSH into Ubuntu)

**Comment by TylerJang27** [comment]
Hi! The message `plugin operations require a valid trunk config` suggests that your current configuration is invalid. Could you try the following for me:
1. Delete your `~/.cache/trunk/plugins` folder, it's possible something got into a bad state with plugin caches.
2. Update your `.trunk/trunk.yaml` manually to use plugins `v1.5.0` and CLI version `1.22.0`
3. Run `trunk check`. If there is still an error, please post it here.

**Comment by remkolems** [comment]
## Steps taken
In the end I uninstalled everything, thus 
- `trunk` cli at `/usr/local/bin/trunk` 
- VSCode extension
- removed all `.trunk  folder from git repo
- removed `~/.cache/trunk`

So in the end I used 
- `curl https://get.trunk.io -fsSL | bash` to install `trunk`
- executed command `trunk --version`, that installed `trunk v1.22.1`
- `trunk init` in git repo
- `trunk check` 

## Brew issues
Reinstalled `trunk` initially with `brew install trunk-io`, but that caused a major headache. Brew do not know `trunk-io`, but it suggests `brew install trunk` which is incorrect.  Brew tells you btw ... but in the consternation you might use that suggestion. As I did.

## Resolved
`trunk cli v1.22.1` completely changed my `trunk.yaml` file --> no errors anymore.

@TylerJang27 Thank you for your guidance and quick feedback. Appreciated!

For reference purposes

```yaml
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.22.1
# Many linters and tools depend on runtimes - configure them here. (https://docs.trunk.io/runtimes)
runtimes:
  enabled:
    - go@1.19.5
    - node@18.12.1
    - python@3.10.8
# This is the section where you manage your linters. (https://docs.trunk.io/check/configuration)
lint:
  enabled:
    - checkov@3.2.128
    - git-diff-check
    - hadolint@2.10.0
    - markdownlint@0.41.0
    - osv-scanner@1.3.6
    - prettier@3.3.1
    - renovate@37.399.0
    - shellcheck@0.8.0
    - shfmt@3.6.0
    - terrascan@1.18.1
    - trivy@0.37.1
    - trufflehog@3.31.3
    - yamllint@1.35.1
actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
```
