### ISSUE TITLE
perltidy isn't installed when enabled

### ISSUE THREAD

**Issue by docwhat** [trunk-io/plugins#806]
When using `perltidy`, it fails if it isn't installed on the host system.

This is problematic in CI:

Example:

<https://github.com/docwhat/bashables/actions/runs/9483902974/job/26132129649>

```yaml
# .trunk/out/ppqBs.yaml
  trunk_cli_version: 1.22.1
  title: "Error while executing: tests/test_helper/pseudo-tty.pl"
  report:
    - message: Unable to find binary in PATH
      binary: perltidy
      PATH:
        - /home/runner/.local/share/bats/bin
        - /snap/bin
        - /home/runner/.local/bin
        - /opt/pipx_bin
        - /home/runner/.cargo/bin
        - /home/runner/.config/composer/vendor/bin
        - /usr/local/.ghcup/bin
        - /home/runner/.dotnet/tools
        - /usr/local/sbin
        - /usr/local/bin
        - /usr/sbin
        - /usr/bin
        - /sbin
        - /bin
        - /usr/games
        - /usr/local/games
        - /snap/bin
    - linter:
        command: |
  
        stdin_path: (none)
        run_from: ""
        timeout: 0
        rerun: ""
        exit_status: exited
        exit_code: 0
        stdout: (none)
        stderr: (none)
      parser: |
        (none)
```

The commit message for 097a7d3e305964d73e1205638430039e341e93d1 says this was done deliberately.

I can be convinced that we don't need to install a local perl runtime, but the command should be installed at the very least with a custom, trunk-specific `PERL5LIB`.

**Comment by docwhat** [comment]
I think that this issue is causing the Merge "Check" in app.trunk.io to always fail.

In app.trunk.io I get an error every commit. For example, for [docwhat/bashables commit c15f5c6](https://github.com/docwhat/bashables/commit/c15f5c61ae1dce2240dcd77fa9e4a568573ff25b) I get:

**perltidy** `tests/test_helper/pseudo-tty.pl`

```
trunk_cli_version: 1.22.1
title: "Error while executing: tests/test_helper/pseudo-tty.pl"
report:
  - message: Unable to find binary in PATH
    binary: perltidy
    PATH:
      - /snap/bin
      - /home/runner/.local/bin
      - /opt/pipx_bin
      - /home/runner/.cargo/bin
      - /home/runner/.config/composer/vendor/bin
      - /usr/local/.ghcup/bin
      - /home/runner/.dotnet/tools
      - /usr/local/sbin
      - /usr/local/bin
      - /usr/sbin
      - /usr/bin
      - /sbin
      - /bin
      - /usr/games
      - /usr/local/games
      - /snap/bin
  - linter:
      command: |

      stdin_path: (none)
      run_from: ""
      timeout: 0
      rerun: ""
      exit_status: exited
      exit_code: 0
      stdout: (none)
      stderr: (none)
    parser: |
      (none)
```

At the very least, the docker container or VM used to run Trunk Check should have `perltidy` and `perlcritic` pre-installed.
