### ISSUE TITLE
How to run txtpbfmt on text proto files?

### ISSUE THREAD

**Issue by Skoti** [trunk-io/plugins#832]
I've enabled `txtpbfmt` linter and the `trunk.yaml` now contains `- txtpbfmt@0.0.0-20230412060525-fa9f017c0ded`.
However, when I try to format a `pbtxt` or `txtpb` file in VSCode it does nothing.
The same happens when executing directly:
```shell
❯ trunk fmt path/to/myfile.txtpb
Checking 100% [===========================================================================================>]  4/4  1.0s

Found no applicable linters for the requested path
```

I've tried modifying the `lint` section, in the `plugin.yaml` file for `txtpbfmt`, as instructed by the [documentation](https://docs.trunk.io/code-quality/configuration/integrating-linters/files#applicable-filetypes):
```yaml
version: 0.1
tools:
  definitions:
    - name: txtpbfmt
      runtime: go
      package: github.com/protocolbuffers/txtpbfmt/cmd/txtpbfmt
      shims: [txtpbfmt]
      known_good_version: 0.0.0-20230412060525-fa9f017c0ded
lint:
  files:
    - name: textproto2
      extensions:
        - pbtxt
        - txtpb
        - textpb
        - textproto
  definitions:
    - name: txtpbfmt
      files: [textproto2]
      tools: [txtpbfmt]
      description: A formatter for textproto files
      commands:
        - name: format
          output: rewrite
          run: txtpbfmt ${target}
          success_codes: [0]
          in_place: true
          batch: true
          formatter: true
      suggest_if: files_present
      known_good_version: 0.0.0-20230412060525-fa9f017c0ded
```

but it hasn't changed anything.

Originally, this [file](https://github.com/trunk-io/plugins/blob/main/linters/txtpbfmt/plugin.yaml) has `[textproto]` in its `files` node but I couldn't find any corresponding definition of what file extensions it actually involves.

Anyway, running the tool directly formats the file as expected:
```shell
cd ~/.cache/trunk/tools/txtpbfmt/0.0.0-20230412060525-fa9f017c0ded-94ed989503ec614c4f8140258ed9defd/bin
./txtpbfmt path/to/myfile.txtpb
```
Clearly, something is wrong with the configuration of this tool in `trunk`.

**Comment by TylerJang27** [comment]
Hi! Sorry you're running into this. Fyi, our file definitions are defined here, one level up in the [`linters/plugin.yaml`](https://github.com/trunk-io/plugins/blob/main/linters/plugin.yaml#L602-L607). That original definition does not include `txtpb`, so we likely need to update that.

After adding your files override, I am able to run on a `myfile.txtpb` with no issues. It's possible you have ignores applied that are preventing it from being run. Assuming that you have `txtpbfmt` and (`trufflehog` or `git-diff-check`) enabled, your `trunk check --verbose -n path/to/myfile.txtpb` should look something like this:

![Screenshot 2024-07-25 at 10 17 29 AM](https://github.com/user-attachments/assets/9350d0a4-f1d6-41de-84e5-ee58fa4fec83)

Can you run that verbose command (with `check`, not `fmt`) and lmk what you see?

**Comment by Skoti** [comment]
Thanks for a quick reply!

Here is the output:
```shell
Checking 100% [===========================================================================================>]  9/9  0.8s

  ACTIONS

path/to/myfile.txtpb
 git-diff-check  .trunk/out/GRB9V.yaml  lint
 gitleaks        [cached]               lint

Checked 1 file
✔ No issues
```

**Comment by TylerJang27** [comment]
Hmm, it's not globally or git ignored so it should be running but clearly is not. Do you mind pasting your full `.trunk/trunk.yaml`, and I can try to repro?

**Comment by Skoti** [comment]
```yaml
version: 0.1
cli:
  version: 1.22.2
plugins:
  sources:
    - id: trunk
      ref: v1.6.1
      uri: https://github.com/trunk-io/plugins
lint:
  enabled:
    - buf-format@1.35.1
    - actionlint@1.7.1
    - black@24.4.2
    - buildifier@7.1.2
    - dotenv-linter@3.3.0
    - git-diff-check
    - gitleaks@8.18.4
    - hadolint@2.12.0
    - isort@5.13.2
    - ktlint@1.3.1
    - markdownlint@0.41.0
    - oxipng@9.1.2
    - prettier@3.3.3
    - ruff@0.5.4
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - svgo@3.3.2
    - taplo@0.9.2
    - tflint@0.52.0
    - txtpbfmt@0.0.0-20230412060525-fa9f017c0ded
    - yamllint@1.35.1
runtimes:
  enabled:
    - go@1.21.0
    - java@13.0.11
    - node@18.12.1
    - python@3.10.8
actions:
  disabled:
    - git-lfs
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
  enabled:
    - trunk-upgrade-available

```

**Comment by TylerJang27** [comment]
And adding 
```yaml
  files:
    - name: textproto
      extensions:
        - pbtxt
        - txtpb
        - textpb
        - textproto
```
to the `lint` section doesn't resolve it?
