### ISSUE TITLE
psscriptanalyzer hanging

### ISSUE THREAD

**Issue by sheldonhull** [trunk-io/plugins#840]
I'm on latest version of trunk `1.22.2` and plugins were just updated `v1.6.1`.
I love that there is a `psscriptanalyzer` option, but this is the second time I've tried to use and both had timeouts.

Never seems to return and just hangs.

config that seems relevant.
Any idea what might be causing this?

```yaml
version: '0.1'
cli:
  version: 1.22.2
  shell_hooks:
    path_add:
      - '${workspace}/tools'
plugins:
  sources:
    - id: trunk
      ref: v1.6.1
      uri: https://github.com/trunk-io/plugins
lint:
  enabled:
    - psscriptanalyzer@1.22.0
tools:
  enabled:
    - converttosarif@1.0.0
    - pwsh@7.4.4

```

![CleanShot 2024-08-05 at 18 38 41](https://github.com/user-attachments/assets/d01e65e0-52c9-4865-b4a1-587da335b540)

![CleanShot 2024-08-05 at 18 40 57](https://github.com/user-attachments/assets/f64b77ba-39d6-4126-954b-b3f9c6590272)

This also applied when I tried to run `trunk fmt` first, and it kept hanging.
