### ISSUE TITLE
New linter request: `squawk`

### ISSUE THREAD

**Issue by fnimick** [trunk-io/plugins#857]
This is a new linter in development for postgres migrations.

I have a local custom config set up, as an example:

```
    - name: squawk
      files:
        - sql
      commands:
        - name: lint
          run: npx squawk --reporter Gcc ${target}
          output: regex
          success_codes: [0, 1]
          parse_regex: "(?P<path>.*):(?P<line>\\d+):(?P<col>\\d+): (?P<severity>\\S*) (?P<code>\\S*) (?P<message>.*)"
```

NOTE: the line number output is currently not working, tracked at https://github.com/sbdchd/squawk/issues/373
