### ISSUE TITLE
Unexpected error of golangci-lint by `trunk check -a`

### ISSUE THREAD

**Issue by yu-iskw** [trunk-io/plugins#869]
## Overview

I got an unexpected violation of golangci-lint with a `trunk check -a` command.

## Expected behavior

We don't the violation even with the `-a` option.

## How to reproduce

I encountered the enexpected behavior, when I developed a terraform provider based on the scafolding framework.

https://github.com/hashicorp/terraform-provider-scaffolding-framework

```shell
# Clone the 
git clone git@github.com:hashicorp/terraform-provider-scaffolding-framework.git

# Set up truk
trunk init

# Run trunk
## I got the violation with the `-a` option
$ trunk check -a
Checking 100% [=================================================================================================================>]  10/10  1.0s

  ISSUES

tools:0:0
 0:0  high  typechecking error: build constraints exclude all Go files in                                                    golangci-lint/error
            /Users/yu/local/src/github/terraform-provider-scaffolding-framework/tools

## I didn't get the violation by passing the root directly
$ trunk check .
Checking 100% [=================================================================================================================>]  10/10  1.0s

Checked 3 files
1 existing issue (use --show-existing to see it)
✔ No new issues
```

## NOTE: behavior of golangci-lint

```shell
# I didn't get anything if passing the root directly
$ golangci-lint run .

# I got the same violation if speciflyng the 'tools' directory.
$ golangci-lint run tools/
ERRO [linters_context] typechecking error: build constraints exclude all Go files in /Users/yu/local/src/github/terraform-provider-scaffolding-framework/tools
```

**Comment by det** [comment]
Hi @yu-iskw,

I think you want to ignore the tools directory for go files by merging the following into your `.trunk/trunk.yaml`:

```
lint:
  ignore:
    - linters: [golangci-lint]
      paths: [tools/**]
```

**Comment by yu-iskw** [comment]
@det Thank you for the advice. I tried that. But I encountered the violation as well. Is there anythong wrong I should fix?

## Trunk command

I executed the subsequent trunk command with the config file below. 

```shell
$ trunk check -a
Checking 100% [=================================================================================================================>]  10/10  0.9s

  ISSUES

tools:0:0
 0:0  high  typechecking error: build constraints exclude all Go files in                                                    golangci-lint/error
            /Users/yu/local/src/github/terraform-provider-scaffolding-framework/tools

Checked 3 files
✖ 1 lint issue
```

## `.trunk/trunk.yaml`

```yaml
version: 0.1
cli:
  version: 1.22.5
plugins:
  sources:
    - id: trunk
      ref: v1.6.2
      uri: https://github.com/trunk-io/plugins
runtimes:
  enabled:
    - go@1.21.0
    - node@18.12.1
    - python@3.10.8
lint:
  ignore:
    - linters: [golangci-lint]
      paths: [tools/**]
  enabled:
    - golangci-lint@1.61.0
actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
```
