### ISSUE TITLE
Ruff import sorted broken on plugin version 1.6.2

### ISSUE THREAD

**Issue by Ryang20718** [trunk-io/plugins#894]
with trunk cli 1.22.6, ruff 0.6.9 and plugin 1.6.2, ruff fails to sort imports. this works on 1.6.1

i.e
```
import os
import json
```

```
 definitions:
    - name: ruff
      commands:
        - name: lint
          formatter: false
        - name: format
          output: rewrite
          run: ruff format --line-length=120 ${target}
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          formatter: true
        - name: isort # this is the only way to have ruff run isort on trunk fmt/save
          output: rewrite
          run: ruff check --select I --fix --line-length=120 ${target} # we only run isort here
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          formatter: true
```

**Comment by TylerJang27** [comment]
This is an issue with your overrides. We try to keep overrides forward compatible (that is to say backwards compatible plugins releases), but sometimes they break with larger changes. In this case you need to set:

```yaml
    - name: ruff
      commands:
        - name: lint
          files: [python, python-interface]
          formatter: false
        - name: format
          files: [python, python-interface]
          output: rewrite
          run: ruff format --line-length=120 ${target}
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          enabled: true
          formatter: true
        - name: isort # this is the only way to have ruff run isort on trunk fmt/save
          files: [python, python-interface]
          output: rewrite
          run: ruff check --select I --fix --line-length=120 ${target} # we only run isort here
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          formatter: true
```

**Comment by Ryang20718** [comment]
```
    - name: ruff
      files: [python, python-interface, jupyter]
      commands:
        - name: lint
          formatter: false
        - name: format
          output: rewrite
          run: ruff format --line-length=120 ${target}
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          formatter: true
        - name: isort # this is the only way to have ruff run isort on trunk fmt/save
          output: rewrite
          run: ruff check --select I --fix --line-length=120 ${target} # we only run isort here
          success_codes: [0]
          batch: true
          in_place: true
          allow_empty_files: false
          cache_results: false
          formatter: true
```
