### ISSUE TITLE
Trunk check not working with ESLint 9.18.0

### ISSUE THREAD

**Issue by mapringg** [trunk-io/plugins#962]
```
# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
cli:
  version: 1.22.9
# Trunk provides extensibility via plugins. (https://docs.trunk.io/plugins)
plugins:
  sources:
    - id: trunk
      ref: v1.6.6
      uri: https://github.com/trunk-io/plugins
# Many linters and tools depend on runtimes - configure them here. (https://docs.trunk.io/runtimes)
runtimes:
  enabled:
    - node@18.20.5
    - python@3.10.8
# This is the section where you manage your linters. (https://docs.trunk.io/check/configuration)
lint:
  enabled:
    - eslint@9.18.0
    - prettier@3.4.2
    - actionlint@1.7.6
    - checkov@3.2.353
    - git-diff-check
    - markdownlint@0.43.0
    - osv-scanner@1.9.2
    - svgo@3.3.2
    - trufflehog@3.88.2
    - yamllint@1.35.1
  disabled:
actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
```

```
trunk_cli_version: 1.22.9
title: eslint exited with exit_code=2
report:
  - eslint exited with exit_code=2
  - ~
  - linter:
      command: |
        /home/mapring/.cache/trunk/tools/eslint/9.18.0-6e989d136992a80c3a22176ffdadc697/node_modules/.bin/eslint --output-file /tmp/trunk-1000/C1AgFv/VxkUkFldnwPy --format json 'src/app/(main)/dashboard/_components/todo-list.tsx'
      stdin_path: (none)
      run_from: /tmp/trunk-1000/nuSO2W/6iAubG
      timeout: 10m
      rerun: (cd /tmp/trunk-1000/nuSO2W/6iAubG; env -i PATH=/home/mapring/.cache/trunk/tools/eslint/9.18.0-6e989d136992a80c3a22176ffdadc697/node_modules/.bin:/home/mapring/.cache/trunk/tools/node/18.20.5-91fada217876835b75c56bdb0a8857f8/bin:/home/mapring/.cache/trunk/tools/node/18.20.5-91fada217876835b75c56bdb0a8857f8:/home/mapring/.local/share/mise/installs/go/1.23.5/bin:/home/mapring/.local/share/mise/installs/node/22.13.0/bin:/home/mapring/.local/share/mise/installs/bun/1.1.45/bin:/home/mapring/.local/share/mise/installs/deno/2.1.6/bin:/home/mapring/.local/share/mise/installs/deno/2.1.6/.deno/bin:/home/mapring/.local/share/mise/installs/python/3.12.8/bin:/home/mapring/.local/share/mise/installs/pipx-git-https-github-com-aider-ai-aider-git/v0.71.1/bin:/home/mapring/.local/share/mise/shims:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/opt/mise/bin:/home/mapring/.cargo/bin:/home/mapring/.local/bin:/home/mapring/Android/Sdk/platform-tools:/home/mapring/Android/Sdk/emulator:/home/mapring/bin:/tmp/.mount_cursorqpXfZl:/tmp/.mount_cursorqpXfZl/usr/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/mapring/.local/bin:/home/mapring/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin HOME=/home/mapring NODE_PATH=/home/mapring/.cache/trunk/tools/eslint/9.18.0-6e989d136992a80c3a22176ffdadc697/node_modules /home/mapring/.cache/trunk/tools/eslint/9.18.0-6e989d136992a80c3a22176ffdadc697/node_modules/.bin/eslint --output-file /tmp/trunk-1000/C1AgFv/VxkUkFldnwPy --format json 'src/app/(main)/dashboard/_components/todo-list.tsx')
      affects_cache:
        - package.json
        - tsconfig.json
      direct_configs:
        - eslint.config.mjs
      exit_status: exited
      exit_code: 2
      stdout: (none)
      stderr: |

        Oops! Something went wrong! :(

        ESLint: 9.18.0

        Error: Cannot read config file: /home/mapring/Developer/dsp-master-client/node_modules/.pnpm/eslint-config-next@15.1.5_eslint@9.18.0_jiti@2.4.2__typescript@5.7.3/node_modules/eslint-config-next/index.js
        Error: Failed to patch ESLint because the calling module was not recognized.
        If you are using a newer ESLint version that may be unsupported, please create a GitHub issue:
        https://github.com/microsoft/rushstack/issues
        Referenced from: /home/mapring/Developer/dsp-master-client/node_modules/.pnpm/eslint-config-next@15.1.5_eslint@9.18.0_jiti@2.4.2__typescript@5.7.3/node_modules/eslint-config-next/core-web-vitals.js
            at Object.<anonymous> (/home/mapring/Developer/dsp-master-client/node_modules/.pnpm/@rushstack+eslint-patch@1.10.5/node_modules/@rushstack/eslint-patch/lib/_patch-base.js:167:19)
            at Module._compile (node:internal/modules/cjs/loader:1364:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
            at Module.load (node:internal/modules/cjs/loader:1203:32)
            at Module._load (node:internal/modules/cjs/loader:1019:12)
            at Module.require (node:internal/modules/cjs/loader:1231:19)
            at require (node:internal/modules/helpers:177:18)
            at Object.<anonymous> (/home/mapring/Developer/dsp-master-client/node_modules/.pnpm/@rushstack+eslint-patch@1.10.5/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:11:23)
            at Module._compile (node:internal/modules/cjs/loader:1364:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

    parser: |
      (none)
```
```
import path from "node:path"
import { fileURLToPath } from "node:url"
import { FlatCompat } from "@eslint/eslintrc"
import js from "@eslint/js"
import tsParser from "@typescript-eslint/parser"
import reactCompiler from "eslint-plugin-react-compiler"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
})

const config = [
  ...compat.extends(
    "next/core-web-vitals",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "plugin:tailwindcss/recommended"
  ),
  {
    plugins: {
      "react-compiler": reactCompiler,
    },

    languageOptions: {
      parser: tsParser,
    },

    rules: {
      "react-compiler/react-compiler": "error",
    },
  },
]

export default config
```

My eslint config works with the vscode eslint extension. Please tell me if you need more log.
