### ISSUE TITLE
osv-scanner.toml not recognized in trunk configs folder

### ISSUE THREAD

**Issue by mattjohnsonpint** [trunk-io/plugins#976]
[The docs](https://docs.trunk.io/code-quality/linters/supported/osv-scanner#settings) say that you can move the `osv-scanner.toml` file to `.trunk/configs` - but this doesn't work.  A false positive reported by osv-scanner can only be ignored by placing an `osv-scanner.toml` file in the same directory as the file with the error.  In a large project, this can mean lots of copies of this file.

**Comment by mattjohnsonpint** [comment]
I found a workaround by adding this to my `trunk.yaml`

```yaml
lint: 
  definitions:
    - name: osv-scanner
      commands:
        - name: scan
          run:
            osv-scanner --lockfile=${target} --format json --config=.trunk/configs/osv-scanner.toml
```

That overrides the run command to pass the `--config` path to osv scanner.  Is this the correct approach, or is there a better way to deal with this?  Thanks.
